# Generated by Django 2.2.1 on 2020-02-27 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xcx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品id')),
                ('status', models.CharField(default=1, max_length=20, verbose_name='是否禁用 1用 0禁')),
                ('Commodity_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('Comodity_introduction', models.CharField(default='暂无介绍', max_length=200, verbose_name='商品简介')),
                ('Comodity_Specifications', models.CharField(max_length=20, verbose_name='商品规格')),
                ('Commodity_Company', models.CharField(max_length=20, verbose_name='商品计量单位')),
                ('Commodity_money', models.CharField(max_length=20, verbose_name='商品价格')),
                ('Commodity_details', models.TextField(max_length=2000, verbose_name='商品详情')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_login_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '商品表',
            },
        ),
        migrations.CreateModel(
            name='Commodity_pic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片id')),
                ('status', models.CharField(default=1, max_length=20, verbose_name='是否禁用 1用 0禁')),
                ('pic_path', models.CharField(max_length=200, verbose_name='商品图片路径')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Commodity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcx.Commodity', verbose_name='商品id')),
            ],
            options={
                'verbose_name': '商品图片表',
            },
        ),
    ]
