# Generated by Django 2.2.1 on 2020-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcx', '0002_commodity_commodity_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='Comodity_type',
            field=models.CharField(default=None, max_length=20, verbose_name='模块'),
        ),
    ]
