# Generated by Django 2.2.1 on 2020-02-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcx', '0003_commodity_comodity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity_pic',
            name='Commodity_id',
            field=models.CharField(max_length=20, verbose_name='商品id'),
        ),
    ]
