# Generated by Django 2.2.1 on 2020-02-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcx', '0004_auto_20200227_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='user_id',
            field=models.CharField(default=None, max_length=20, verbose_name='创建人'),
        ),
    ]
